name: calcium_imaging_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - scipy


  - scikit-learn

  - matplotlib
  - bokeh

  - pyyaml
  - pytables
  - opencv

  - pip:
      - pyMou@git+https://github.com/mb-BCA/pyMOU.git@master

      - networkx
      - Shapely

      # ?
      - psutil

      # Windows workaround for h5py
      - wheel
      - cython
      - versioned-hdf5
      - h5py

